[package]
name = "dedup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
clap = "3.1.6"
clap_complete = "3.1.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
configparser = "3.0.0"
dirs = "4.0.0"
flate2= { version = "1.0.22", features = ["rust_backend"] }


[[bin]]
name = "dedup"
path = "main.rs"
