[package]
name = "rust-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3"
rb_tree = { version = "0.5", features = ["serde"] }
clap = { version = "3.1.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap_complete = "3.1.1"

[[bin]]
name = "rust-play"
path = "main.rs"
